### ISSUE TITLE
스크롤바 버그

### ISSUE THREAD

**Issue by BackdevHong** [Nayejun/Yelio#2]
![스크롤1](https://user-images.githubusercontent.com/97325091/175890073-33b10894-a3e2-4db3-a94a-0dd2269eb5b2.png)
![스크롤2](https://user-images.githubusercontent.com/97325091/175890079-eac1145e-fb75-423e-b709-327c96370bb1.png)

윈도우 11, 크롬 기준 스크롤바가 생기는 버그가 있습니다.

**Comment by coodns** [comment]
<img width="319" alt="Screen Shot 2022-08-19 at 4 26 29 PM" src="https://user-images.githubusercontent.com/69895368/185566538-fd0e13b1-4e5d-423f-81ae-186c029ef8e8.png">
